import { Admin } from "../Layout/admin";
import Head from "next/head";
import { Popup } from '../Components/Popup'
import { useState } from "react";

export default function billing() {

	const [showPopup, setShowPopup] = useState(false);


	const ready = () => {
		setShowPopup(true);
	};

	const done = () => {
		setShowPopup(false);
	};

	const cancel = () => {
		setShowPopup(false)
	};

	return (
		<>
			<Head>
				<title>Billing</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Admin>
				<>
					<main className="flex w-full justify-center">
						<div className="w-full py-4 px-2 md:px-4 lg:px-4 md:grid md:grid-cols-3 lg:grid lg:grid-cols-5 space-x-2 space-y-2 h-[90vh] overflow-auto">
							<div className="rounded-md max-w-full min-w-[20px] bg-slate-300 max-h-[22rem]">
								<div className="flex justify-center bg-[#494449] rounded-t-md py-2">
									<h1 className="text-white">Table 1</h1>
								</div>
								<h2 className="text-center px-4 py-1 flex justify-between pb-2">Name<span className="">Qty.</span> <span className=""> PC.</span></h2>
								<div>
									<div className="max-h-[10rem] overflow-auto">
										<p className="text-center px-4 py-1 flex justify-between text-[#494449]">item 2 <span className="ml-4">3</span><span className="ml-4">100</span></p>
										<p className="text-center px-4 py-1 flex justify-between text-[#494449]">item 2 <span className="ml-4">1</span><span className="ml-4">50</span></p>
										<p className="text-center px-4 py-1 flex justify-between text-[#494449]">item 2 <span className="ml-4">4</span><span className="ml-4">40</span></p>
										<p className="text-center px-4 py-1 flex justify-between text-[#494449]">item 2 <span className="ml-4">4</span><span className="ml-4">30</span></p>
										<p className="text-center px-4 py-1 flex justify-between text-[#494449]">item 2 <span className="ml-4">4</span><span className="ml-4">110</span></p>
									</div>
									<div className="flex justify-between bg-[#494449] rounded-t-md py-2 px-2">
										<h2 className="border border-white text-white px-4 py-1 rounded-sm">Total P.  000</h2>
										<h2 className="border border-white text-white px-4 py-1 rounded-sm">Total Q. 00</h2>
									</div>
									<div className="flex justify-center relative mt-4 mb-2">
										<button onClick={() => ready()} className="bg-[#494449] text-white px-4 py-1 rounded-md">Pay</button>
									</div>
								</div>
							</div>
						</div>
					</main>
					{showPopup ? (
						<Popup close={done} cancel={cancel} name='Your payment succesfully' />
					) : (
						<></>
					)}
				</>
			</Admin>
		</>
	)
}
